import type { Metadata } from "next";
import "./globals.css";
import { HorizontalNavBar } from "@/components/horizontal-nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-shark">
        <HorizontalNavBar />
        <main className="ml-20">{children}</main>
      </body>
    </html>
  );
}
